name: Lenguage4U CI - Unit Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      - name: Install flutter 
        uses: subosito/flutter-action@v3
        with:
          channel: "stable"
      - name: Clean proyect
        run: flutter clean
      - name: Get packages
        run: flutter pub get
      - name: Build runner
        run: flutter pub run build_runner build
      - name: Run unit tests
        run: flutter test --coverae
      - name: Publish coverage to codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
